CPP=g++
PROGS=chartype exceed hexoct1 hexoct2 limits morechar bondini floatnum fltadd arith divide modulus init typecast

chartype:
	$(CPP) chartype.cpp -o chartype

exceed:
	$(CPP) exceed.cpp -o exceed

hexoct1:
	$(CPP) hexoct1.cpp -o hexoct1

hexoct2:
	$(CPP) hexoct2.cpp -o hexoct2

limits:
	$(CPP) limits.cpp -o limits

morechar:
	$(CPP) morechar.cpp -o morechar

bondini:
	$(CPP) bondini.cpp -o bondini

floatnum:
	$(CPP) floatnum.cpp -o floatnum

fltadd:
	$(CPP) fltadd.cpp -o fltadd

arith:
	$(CPP) arith.cpp -o arith

divide:
	$(CPP) divide.cpp -o divide

modulus:
	$(CPP) modulus.cpp -o modulus

init:
	$(CPP) init.cpp -o init

typecast:
	$(CPP) typecast.cpp -o typecast

all : $(PROGS)

clean:
	rm -f $(PROGS)
