CPP=g++
PROGS=ex1 ex2 ex3 ex4 ex5 ex6 ex7

ex1:
	$(CPP) ex1.cpp -o ex1

ex2:
	$(CPP) ex2.cpp -o ex2

ex3:
	$(CPP) ex3.cpp -o ex3

ex4:
	$(CPP) ex4.cpp -o ex4

ex5:
	$(CPP) ex5.cpp -o ex5

ex6:
	$(CPP) ex6.cpp -o ex6

ex7:
	$(CPP) ex7.cpp -o ex7

all : $(PROGS)

clean:
	rm -f $(PROGS)
